---
- hosts: scalausb
  vars:
    home: "~/Documents/inoio/ScalaSeminarWorkspace/ScalaUSBStick"
    scalaVersion: "2.11.4"
    sbtVersion: "0.13.7"
    sbtUrl: "https://dl.bintray.com/sbt/native-packages/sbt/{{sbtVersion}}/sbt-{{sbtVersion}}.{{item.ending}}"
    scalaIdeDownload: "http://downloads.typesafe.com/scalaide-pack/3.0.3.vfinal-210-20140327/"
    scalaIdeWin64: "scala-SDK-3.0.3-2.10-win32.win32.x86_64.zip"
    scalaIdeMacOSX: "scala-SDK-3.0.3-2.10-macosx.cocoa.x86_64.zip"
    scalaFile: "scala-{{scalaVersion}}.tgz"
    scalaDocs: "scala-docs-{{scalaVersion}}.zip"
    activatorVersion: "1.2.12"
    activator: "typesafe-activator-{{activatorVersion}}.zip"
    wget: "/usr/local/bin/wget"

  tasks:
  - name: get scala
    command: "{{wget}} http://www.scala-lang.org/files/archive/{{item}} chdir={{home}} creates={{item}}"
    with_items:
      - "{{scalaFile}}"
      - "{{scalaDocs}}"

  - name: get sbt versions
    command: "{{wget}} {{sbtUrl}} -O sbt-{{sbtVersion}}.{{item.ending}} creates=sbt-{{sbtVersion}}.{{item.ending}} chdir={{home}}"
    with_items:
      - { input: "sbt.msi", ending: "msi" }
      - { input: "sbt.zip", ending: "zip" }
      - { input: "sbt.tgz", ending: "tgz" }

  - name: get scala ide versions
    command: "{{wget}} {{scalaIdeDownload}}{{item}} creates={{item}} chdir={{home}}"
    with_items:
      - "{{scalaIdeWin64}}"
      - "{{scalaIdeMacOSX}}"

  - name: get activator
    command: "{{wget}} http://downloads.typesafe.com/typesafe-activator/{{activatorVersion}}/{{activator}} creates={{activator}} chdir={{home}}"

  - name: checkout repository
    command: "git clone https://github.com/oose/ScalaUnterlagen.git Teilnehmer chdir={{home}} creates='Teilnehmer'"

  - name: pull repository
    command: "git pull chdir={{home}}/Teilnehmer"